### ISSUE TITLE
Cover worker API

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/implementing-gradle-plugins#11]
@ghale @oehme @bmuschko Should we cover [worker API](https://docs.gradle.org/release-candidate/userguide/custom_tasks.html#worker_api) in this guide once 4.1 GA is published?

**Comment by oehme** [comment]
Gary is working on a dedicated worker api guide. We can link it from here. One day the worker api will become more seamless, then we should cover it here in favor of "traditional tasks". That's some way in the future though.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #213](https://github.com/gradle/guides/issues/213) via [**ZenHub**](https://www.zenhub.com/)
