### ISSUE TITLE
Cover `Convention` while it's still used by core plugins

### ISSUE THREAD

**Issue by oehme** [gradle-guides/implementing-gradle-plugins#14]
Many plugins need to interact with the `JavaPluginConvention`, but we only cover extensions in the plugin authoring guide. We should explain `Convention` while it is still a thing. Ideally we'd also prioritise its deprecation/removal from the core plugins.

**Comment by bmuschko** [comment]
Created PR https://github.com/gradle-guides/implementing-gradle-plugins/pull/15

**Comment by bmuschko** [comment]
Created PR https://github.com/gradle-guides/implementing-gradle-plugins/pull/15
