### ISSUE TITLE
Embrace sentence-per-line writing technique

### ISSUE THREAD

**Issue by k-mack** [gradle-guides/implementing-gradle-plugins#17]
I am loving this document since I just started to write my own Gradle plugins. This is really a suggestion, not an issue:

To increase the readability of Git diffs and the AsciiDoc source, consider embracing Dan Allen's "sentence per line" writing technique from his "Zen of Writing Asciidoctor" presentation (https://youtu.be/Aq2USmIItrs?t=3505). Contiguous lines will be rendered as a paragraph.

I've found this helpful when writing my own AsciiDocs. I figured I'd suggest it here since `index.adoc` uses a line-per-paragraph, where one line exceeds 700 columns.

**Comment by bmuschko** [comment]
Thanks for the pointer to the talk and the recipe. I wasn't aware of the technique. Will need to watch the whole talk later this week.

The suggestion should probably apply to all guides and not just this one. How about your provide a PR on this [here](https://github.com/gradle-guides/writing-getting-started-guides)? It explains how to write and structure guides. Alternatively, please move the issue over there.

I am going to close the issue for now and keep it mind.

**Comment by k-mack** [comment]
Or it be better suited under the style guide (https://github.com/gradle-guides/style-guide)?

**Comment by bmuschko** [comment]
@k-mack Yes, absolutely. The style guide is where it should go. Thanks for checking!
