### ISSUE TITLE
Javadocs in section "Adding helpful Javadocs to implementation" don't render properly

### ISSUE THREAD

**Issue by bmuschko** [gradle-guides/implementing-gradle-plugins#2]
Currently, Javadocs are render on a single line for example:

`/** * Custom task type for generating files for the provided text. * <p> * The following sample code demonstrates the use of the type in a Gradle build script: * <pre> * task generate(type: Generate) { * fileCount = 5 * } * </pre> */`

https://guides.gradle.org/implementing-gradle-plugins/#adding_helpful_javadocs_to_implementation

**Comment by ysb33r** [comment]
Could be a CSS issue.

How it renders with the Gradle stylesheet:

![prent](https://cloud.githubusercontent.com/assets/907624/25004334/2f23f6cc-2054-11e7-8327-24056a9a095b.png)

How it renders with the default stylesheet:

![prent](https://cloud.githubusercontent.com/assets/907624/25004355/460c385e-2054-11e7-8921-c90da410747d.png)

**Comment by bmuschko** [comment]
For now removed the section until we can figure out the formatting issue.

**Comment by ysb33r** [comment]
The problem is not CSS, but with the custom Asciidoctor extension that we use to post-process the generated file. WHen I tested it previously the extension was not included. No actually testing it in the buidl and removing the extension I can see that it renders correctly. WIll need to look whether there is a better way than the way it is currently being done.

**Comment by ysb33r** [comment]
I have raised this issue as asciidoctor/asciidoctorj-groovy-dsl#13, but wil continue to look to see how it can be resolced locally.

**Comment by ysb33r** [comment]
As our insertion is very bespoke to the guides we can get away without using JSoup and just physically inserting the little bit of HTML we need directly into the output, thus by changing

```groovy
    extensions {
        postprocessor { document, output ->
            if (document.basebackend("html")) {
                def extra = """<div style="padding-top: 10px;"><a href="https://guides.gradle.org"><img src="http://guides.gradle.org/gradle-guides.svg" alt=""></a></div>"""
                output.replaceAll( ~/<div id="header">\s*<h1>/, """<div id="header">${extra}<h1>""")
            } else {
                output
            }
        }
    }
```

**Comment by pioterj** [comment]
I don't have an opinion.
