### ISSUE TITLE
Can't repeat first sample (LatestArtifactVersion)

### ISSUE THREAD

**Issue by etienne-sf** [gradle-guides/implementing-gradle-plugins#29]
Hello,

I'm trying to write a Gradle plugin. But I can't succeed in making the providing samples work.
Even the simplest !
:(

I tried the sample of this part:
https://guides.gradle.org/implementing-gradle-plugins/#writing-and-using-custom-task-types

The code I tried is in this zip file:
[Designing_Gradle_plugins.zip](https://github.com/gradle-guides/implementing-gradle-plugins/files/3379399/Designing_Gradle_plugins.zip)

When I try any build, it complains that is is not capable of resolving the class "com.company.gradle.binaryrepo.LatestArtifactVersion"

What am I doing wrong ?

Etienne

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #291](https://github.com/gradle/guides/issues/291) via [**ZenHub**](https://www.zenhub.com/)
