### ISSUE TITLE
Plugin ala InhouseConventionJavaPlugin but with Extension Question

### ISSUE THREAD

**Issue by chhex** [gradle-guides/implementing-gradle-plugins#30]
I am not quite sure if i am here right with my Question. I am a relativ newbie to the fascinating world of writing Gradle Plugins. Your Guides and Documentation are great.  Maybe my questions can also contribute? 

Background: I want to write a Inhouse specific strongly opinated Plugin, which shortcuts and supplies in-house defaults for the standard MavenPlugin.  Additionally it is also a requirement that the developer is able to "overwrite" the defaults values, where it makes sense. 

So i looked for guidance in the https://github.com/gradle-guides and specifically https://github.com/gradle-guides/implementing-gradle-plugins/blob/master/samples/code/react-to-plugin/buildSrc/src/main/java/InhouseConventionJavaPlugin.java

This was a good starting point. The convention for the Java sourceSets is enforced with 

```
SourceSet main = javaConvention.getSourceSets().getByName(SourceSet.MAIN_SOURCE_SET_NAME);
                main.getJava().setSrcDirs(Arrays.asList("src"));
```

 Now, for my scenario the developer should be able to "overrule" this convention:  it should be only a default, which can be changed. 

So I added a [Extension Class](https://github.com/chhex/impementing-gradle-plugins/blob/master/buildSrc/src/main/java/extensiontest/InhouseConventionJavaExtension.java) for the Plugin  and moved the above SourceSet configuration to a method configure() the Extension Class: 

```
public void configure() {
        JavaPluginConvention javaConvention =
                project.getConvention().getPlugin(JavaPluginConvention.class);
            SourceSet main = javaConvention.getSourceSets().getByName(SourceSet.MAIN_SOURCE_SET_NAME);
            main.getJava().setSrcDirs(Arrays.asList(sourceDir));
	}

```
In the [Plugin class](https://github.com/chhex/impementing-gradle-plugins/blob/master/buildSrc/src/main/java/extensiontest/InhouseConventionJavaPlugin.java) i only apply the JavaPlugin and create the Extension "javaConventions" with the Project instance as constructor arg: 

```
public void apply(Project project) {
		final ExtensionContainer ext = project.getExtensions();
		final PluginContainer plugins = project.getPlugins();
		plugins.apply(JavaPlugin.class);
		ext.create("javaConventions", InhouseConventionJavaExtension.class, project);
	}
```

It seems to work fine, for the following [build.gradle ](https://github.com/chhex/impementing-gradle-plugins/blob/master/build.gradle) i get the expected output: 
```
apply plugin: extensiontest.InhouseConventionJavaPlugin
javaConventions {
	configure()

}
println sourceSets.main.java.srcDirs
javaConventions.sourceDir = "src/main/java"
println sourceSets.main.java.srcDirs
javaConventions.configure()
println sourceSets.main.java.srcDirs
```

My questions: 
1. Is this a valid pattern to  provide reasonable defaults, but which can be changed, for Grade Plugins, for example the MavenPlugin? What disturbs me with this solution is the necessity of javaConventions.configure(). Are there better way to achieve the same?
2. Maybe an example with this variant of the InhouseConventionJavaPlugin would make sense?

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #298](https://github.com/gradle/guides/issues/298) via [**ZenHub**](https://www.zenhub.com/)
