### ISSUE TITLE
Modify example "domain object container" to use ObjectFactory and NamedDomainObjectFactory

### ISSUE THREAD

**Issue by bmuschko** [gradle-guides/implementing-gradle-plugins#9]
Requires 4.2 to be released with the new public API in https://github.com/gradle/gradle/pull/2393.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #211](https://github.com/gradle/guides/issues/211) via [**ZenHub**](https://www.zenhub.com/)
